# Generated by Django 3.1.3 on 2020-12-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_remove_jobpost_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='user',
            field=models.CharField(max_length=150),
        ),
    ]
